"""
single_W_community_analysis.py

Analyze community structure within a single connectivity matrix W.

Requirements:
    pip install numpy matplotlib seaborn networkx scikit-learn

Adapted from code generated by GPT5
"""


import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import SpectralClustering


class ConnectivityService():
    # ============================================================
    # --- Core functions ---
    # ============================================================

    @classmethod
    def symmetrize_affinity(cls, W, abs_val=True):
        """Make W symmetric and optionally positive (for clustering)."""
        A = 0.5 * (W + W.T)
        if abs_val:
            A = np.abs(A)
        np.fill_diagonal(A, 0.0)
        return A

    @classmethod
    def cluster_modularity(cls, W, symmetric=True):
        """Detect communities via modularity maximization (greedy algorithm)."""
        if symmetric:
            G = nx.from_numpy_array(W)
            communities = nx.algorithms.community.greedy_modularity_communities(G, weight='weight')
        else:
            G = nx.from_numpy_array(W, create_using=nx.DiGraph)
            communities = nx.algorithms.community.greedy_modularity_communities(G.to_undirected(), weight='weight')

        labels = -np.ones(W.shape[0], dtype=int)
        for i, comm in enumerate(communities):
            for node in comm:
                labels[node] = i
        return labels

    @classmethod
    def cluster_spectral(cls, W, n_clusters, random_state=0):
        """Spectral clustering on a symmetric affinity matrix."""
        sc = SpectralClustering(n_clusters=n_clusters, affinity='precomputed', random_state=random_state)
        labels = sc.fit_predict(W)
        return labels

    @classmethod
    def compute_community_strengths(cls, W, labels):
        """Compute within- and between-community mean connection strengths."""
        unique = np.unique(labels)
        C = len(unique)
        within = np.zeros(C)
        between = np.zeros((C, C))
        sizes = np.zeros(C, dtype=int)

        for i, c in enumerate(unique):
            idx_c = np.where(labels == c)[0]
            sizes[i] = len(idx_c)
            sub = W[np.ix_(idx_c, idx_c)]
            if len(idx_c) > 1:
                mask = ~np.eye(len(idx_c), dtype=bool)
                within[i] = sub[mask].mean()
            else:
                within[i] = 0.0

            for j, d in enumerate(unique):
                if i == j:
                    continue
                idx_d = np.where(labels == d)[0]
                between[i, j] = W[np.ix_(idx_c, idx_d)].mean()

        return within, between, sizes

    @classmethod
    def reorder_by_community(cls, W, labels):
        """Return matrix reordered by community membership."""
        idx_sorted = np.argsort(labels)
        W_sorted = W[np.ix_(idx_sorted, idx_sorted)]
        return W_sorted, idx_sorted

    # ============================================================
    # --- Visualization ---
    # ============================================================

    @classmethod
    def plot_reordered_matrix(cls, W_sorted, labels_sorted):
        """Plot reordered connectivity matrix."""
        plt.figure(figsize=(6, 5))
        sns.heatmap(W_sorted, cmap='coolwarm', center=0)
        plt.title("Connectivity matrix reordered by community")
        plt.xlabel("Node (sorted by community)")
        plt.ylabel("Node (sorted by community)")
        plt.tight_layout()
        plt.show()

    @classmethod
    def plot_between_matrix(cls, between):
        """Plot mean between-community strengths."""
        plt.figure(figsize=(5, 4))
        sns.heatmap(between, annot=True, fmt=".2f", cmap="viridis")
        plt.title("Between-community mean connectivity")
        plt.xlabel("Community")
        plt.ylabel("Community")
        plt.tight_layout()
        plt.show()

    @classmethod
    def plot_within_bar(cls, within, sizes):
        """Bar plot of within-community mean strengths."""
        plt.figure(figsize=(6, 4))
        plt.bar(range(len(within)), within)
        plt.xlabel("Community")
        plt.ylabel("Mean within-community strength")
        plt.title("Within-community connection strengths")
        for i, s in enumerate(sizes):
            plt.text(i, within[i], f"n={s}", ha="center", va="bottom", fontsize=8)
        plt.tight_layout()
        plt.show()
