#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Map clem_zfish1 neuron segments to a reference brain and skeletonize them.

This script applies ANTs deformation fields to:
    - soma, axon, and dendrite meshes
    - synapse coordinates found in `*_presynapses.csv` / `*_postsynapses.csv`
    - produces mapped OBJ meshes
    - generates skeletons (SWC) with labeled synapses, soma, axon, and dendrite

It wraps `ANTsRegistrationHelpers` from `ANTs_registration_helpers_jbw.py`.

NOTE:
    This version does NOT attempt to convert legacy synapse files.
    It assumes that synapse CSVs (`*_presynapses.csv`, `*_postsynapses.csv`)
    already exist in each neuron folder.

Example usage
-------------
python3 register_and_skeletonize.py \
    --cells-folder "/Users/jonathanboulanger-weill/Harvard University Dropbox/Jonathan Boulanger-Weill/Projects/Zebrafish_CLEM/1. Downloading_neuronal_morphologies_and_metadata/traced_axons_neurons" \
    --transform-prefix "ANTs_transforms/ANTs_dfield" \
    --ants-bin-path /Users/jonathanboulanger-weill/Packages/install/bin \
    --ants-threads 11

Requirements
------------
- Python 3.11+ (or 3.12 with your global environment)
- ANTs installed (`antsRegistration`, `antsApplyTransforms`, etc.)
- ANTs binary folder accessible via --ants-bin-path
- Synapse CSVs already present for each neuron, *not* generated by this script.
"""

from __future__ import annotations

import argparse
import logging
import os
from pathlib import Path

from register_and_skeletonize_helpers import ANTsRegistrationHelpers


# ----------------------------------------------------------------------
# CLI + logging
# ----------------------------------------------------------------------

def setup_logging(level: int = logging.INFO) -> None:
    """Configure basic logging to stdout."""
    logging.basicConfig(
        level=level,
        format="%(asctime)s [%(levelname)s] %(message)s",
    )


def parse_args() -> argparse.Namespace:
    """
    Parse command-line arguments for the mapping & skeletonization script.
    """
    parser = argparse.ArgumentParser(
        description=(
            "Warp clem_zfish1 neurons to a reference brain using precomputed "
            "ANTs deformation fields, and skeletonize the resulting meshes."
        )
    )

    parser.add_argument(
        "--cells-folder",
        type=Path,
        required=True,
        help=(
            "Folder containing per-neuron subfolders with meshes & synapse CSVs, "
            "e.g. clem_zfish1/traced_neurons/all_cells_111224"
        ),
    )
    parser.add_argument(
        "--transform-prefix",
        type=Path,
        required=True,
        help=(
            "Prefix of the ANTs deformation field (without '.nii.gz'), e.g. "
            "clem_zfish1/transforms/clem_zfish1_to_zbrain/ANTs_dfield"
        ),
    )
    parser.add_argument(
        "--ants-bin-path",
        type=Path,
        required=True,
        help="Directory containing ANTs binaries (antsApplyTransforms, antsRegistration, etc.).",
    )
    parser.add_argument(
        "--ants-threads",
        type=int,
        default=8,
        help="Number of threads to use for ANTs.",
    )

    return parser.parse_args()


# ----------------------------------------------------------------------
# Main
# ----------------------------------------------------------------------

def main() -> None:
    """
    Main routine:
    - Loads ANTs helper
    - Iterates through each neuron folder
    - Applies mapping & skeletonization

    Synapses must already be provided as:
        <cell_name>_presynapses.csv
        <cell_name>_postsynapses.csv
    """
    setup_logging()
    logger = logging.getLogger(__name__)

    args = parse_args()
    cells_folder: Path = args.cells_folder
    transform_prefix: Path = args.transform_prefix
    ants_bin_path: Path = args.ants_bin_path
    ants_threads: int = args.ants_threads

    # Set ANTs environment variables for helper module
    os.environ["ANTs_use_threads"] = str(ants_threads)
    os.environ["ANTs_bin_path"] = str(ants_bin_path)

    logger.info("Using ANTs (threads=%s) from %s", ants_threads, ants_bin_path)

    # Instantiate the registration helper
    ants_reg = ANTsRegistrationHelpers()

    # Validate input folder
    if not cells_folder.is_dir():
        raise NotADirectoryError(f"Cells folder not found: {cells_folder}")

    # Discover all cell/axon folders
    cell_dirs = sorted([p for p in cells_folder.iterdir() if p.is_dir()])
    if not cell_dirs:
        logger.warning("No neuron/axon folders found in %s", cells_folder)
        return

    logger.info("Found %d cells/axons to process.", len(cell_dirs))

    # ------------------------------------------------------------------
    # Process each neuron folder
    # ------------------------------------------------------------------
    for idx, cell_dir in enumerate(cell_dirs, start=1):
        cell_name = cell_dir.name
        logger.info("Processing %s (%d/%d)", cell_name, idx, len(cell_dirs))
        print(f"\r→ Processing {idx}/{len(cell_dirs)}: {cell_name}...", end="", flush=True)

       # 1) Convert legacy synapse file (if present) to NG-resolution CSVs
        try:
            ants_reg.convert_synapse_file(
                root_path=cells_folder,
                cell_name=cell_name,
                shift_x=0,
                shift_y=0,
                shift_z=0,
                scale_x=8,
                scale_y=8,
                scale_z=30,
            )
        except Exception as e:
            logger.error("Error in convert_synapse_file for %s: %s", cell_name, e)
            # Continue anyway: map_and_skeletonize_cell can still run if CSVs already exist
        # 2) Map meshes/synapses and skeletonize
        try:
            ants_reg.map_and_skeletonize_cell(
                root_path=cells_folder,
                cell_name=cell_name,
                transformation_prefix_path=transform_prefix,
                input_limit_x=523_776,  # (1024 x pixels - 1) * 512 nm
                input_limit_y=327_168,  # (640 y pixels - 1)  * 512 nm
                input_limit_z=120_000,  # (251 planes - 1)    * 480 nm
                input_scale_x=0.001,    # convert nm to µm for registration
                input_scale_y=0.001,
                input_scale_z=0.001,
            )
        except Exception as e:
            logger.error("Error in map_and_skeletonize_cell for %s: %s", cell_name, e)

    logger.info("Mapping and skeletonization completed for all cells in %s", cells_folder)


if __name__ == "__main__":
    main()